### Initial Placeholders

In [1]:
import numpy as np 

In [5]:
arr = np.array([[1, 2, 3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

## zero

In [8]:
np.zeros(4).astype('int')

array([0, 0, 0, 0])

In [9]:
np.zeros([4, 6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
np.zeros([2, 3, 4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### ones

In [11]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones([3, 8])

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
np.ones([2, 4, 3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### identity

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.eye(N= 2, M= 4, k = 2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### arange

In [30]:
np.arange(20, 40, 12)

array([20, 32])

### linspace

In [31]:
np.linspace(start=5, stop=6)

array([5.        , 5.02040816, 5.04081633, 5.06122449, 5.08163265,
       5.10204082, 5.12244898, 5.14285714, 5.16326531, 5.18367347,
       5.20408163, 5.2244898 , 5.24489796, 5.26530612, 5.28571429,
       5.30612245, 5.32653061, 5.34693878, 5.36734694, 5.3877551 ,
       5.40816327, 5.42857143, 5.44897959, 5.46938776, 5.48979592,
       5.51020408, 5.53061224, 5.55102041, 5.57142857, 5.59183673,
       5.6122449 , 5.63265306, 5.65306122, 5.67346939, 5.69387755,
       5.71428571, 5.73469388, 5.75510204, 5.7755102 , 5.79591837,
       5.81632653, 5.83673469, 5.85714286, 5.87755102, 5.89795918,
       5.91836735, 5.93877551, 5.95918367, 5.97959184, 6.        ])

In [32]:
np.linspace(10, 100, num=10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [34]:
np.linspace(10, 100, num=10, endpoint= False, retstep=True)

(array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.]), 9.0)

### full

In [35]:
np.full(shape=2, fill_value=5)

array([5, 5])

In [36]:
np.full(shape=[2, 2], fill_value=10)

array([[10, 10],
       [10, 10]])

### empty

In [39]:
# uninitialized array.

np.empty([2,3])

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

### random

In [45]:
np.random.randint(2,3) # random number

2

In [46]:
np.random.randn() # standard normal distribution

0.8122554716089868

In [44]:
np.random.random() # [0, 1)

0.46372170939461843

### aggregate functions

In [47]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
# sum of row 1 
arr.sum(axis = 1)[0]

6

In [51]:
arr.sum(axis = 0)

array([5, 7, 9])

### mean

In [53]:
arr.mean(axis = 1)

array([2., 5.])

In [54]:
arr.mean()

3.5

### mode

In [55]:
from scipy import stats
stats.mode(arr)

ModeResult(mode=array([[1, 2, 3]]), count=array([[1, 1, 1]]))

### median

In [56]:
np.median(arr)

3.5

### max , min

In [57]:
arr.max()

6

In [58]:
arr.max(axis= 0)

array([4, 5, 6])

In [59]:
arr = np.array([[-33, 4, 56], [90, -45, 98]])
arr

array([[-33,   4,  56],
       [ 90, -45,  98]])

In [60]:
arr.min(axis = 1)

array([-33, -45])

In [61]:
arr.max(axis = 0)

array([90,  4, 98])

### cumsum

In [62]:
arr.cumsum()

array([-33, -29,  27, 117,  72, 170])

### std

In [63]:
arr.std()

56.49975417842296

### corrcoef
$R_{ij} = \frac{ C_{ij} } { \sqrt{ C_{ii} * C_{jj} } }$

In [64]:
np.corrcoef(arr)

array([[1.        , 0.14627609],
       [0.14627609, 1.        ]])

### comparison

In [65]:
arr1 = np.array([[2, 3, -90], [-40, 5, -45]])

In [66]:
arr1

array([[  2,   3, -90],
       [-40,   5, -45]])

In [67]:
arr

array([[-33,   4,  56],
       [ 90, -45,  98]])

In [68]:
arr > arr1

array([[False,  True,  True],
       [ True, False,  True]])

In [69]:
arr < 3

array([[ True, False, False],
       [False,  True, False]])

In [70]:
np.array_equal(arr, arr1)

False

### sorting

In [71]:
arr1.sort(axis = 0)

In [72]:
arr1

array([[-40,   3, -90],
       [  2,   5, -45]])

In [73]:
arr1.sort(axis = 1)
arr1

array([[-90, -40,   3],
       [-45,   2,   5]])

In [74]:
arr.sort()
arr

array([[-33,   4,  56],
       [-45,  90,  98]])

### copy

In [75]:
arc = arr.copy()
arc

array([[-33,   4,  56],
       [-45,  90,  98]])

In [79]:
arc[0][2] = 95
arc

array([[  5,   5,  95],
       [-45,  90,  98]])

In [80]:
arr

array([[-33,   4,  56],
       [-45,  90,  98]])

### view

In [81]:
arv = arr.view()

In [82]:
arv

array([[-33,   4,  56],
       [-45,  90,  98]])

In [83]:
arv[0][2] = 95
arv

array([[-33,   4,  95],
       [-45,  90,  98]])

In [84]:
arr

array([[-33,   4,  95],
       [-45,  90,  98]])