In [1]:
import numpy as np 
np.__version__

'1.20.1'

In [4]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [5]:
arr.ndim

1

In [7]:
arr = np.array([[0, 0, 0]])
arr.ndim

2

In [8]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d.ndim

2

In [9]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr_3d = np.array([[[1, 2], [3, 4], [5,6]]])
arr_3d

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [12]:
np.array(50).ndim

0

### Insepction of Arrays

In [14]:
arr.ndim

2

In [15]:
len(arr)

1

In [16]:
arr

array([[0, 0, 0]])

In [17]:
arr.size

3

In [21]:
arr_2d.shape

(2, 3)

In [22]:
arr_2d.dtype

dtype('int64')

In [23]:
arr_2d.dtype.name

'int64'

In [24]:
np.array([True, False]).astype('int')

array([1, 0])

In [25]:
np.array([2,3,4], ndmin = 5)

array([[[[[2, 3, 4]]]]])

### Array Mathematics

In [26]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

In [27]:
np.add(a,b)

array([4, 6, 8])

In [28]:
a + b

array([4, 6, 8])

In [29]:
a - b

array([-2, -2, -2])

In [30]:
a * b

array([ 3,  8, 15])

In [31]:
a / b

array([0.33333333, 0.5       , 0.6       ])

In [32]:
a **b

array([  1,  16, 243])

In [33]:
a % b

array([1, 2, 3])

In [34]:
np.multiply(a,b)

array([ 3,  8, 15])

In [35]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [36]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [37]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [38]:
np.sin(np.tan(b))

array([-0.14206429,  0.91593089,  0.23665573])

In [39]:
a,b

(array([1, 2, 3]), array([3, 4, 5]))

In [40]:
np.dot(a,b)

26