In [1]:
import numpy as np 

## Aggregate Functions

In [2]:
a = np.array([[11, 22], [33,44]])
print(a)

[[11 22]
 [33 44]]


In [3]:
b = np.array([[12, 24],[13, 39]])
print(b)

[[12 24]
 [13 39]]


In [4]:
c = a + b 
print(c)

[[23 46]
 [46 83]]


In [5]:
# sum
print(c.sum(axis=1))

[ 69 129]


In [6]:
# mean
np.mean(a)

27.5

In [7]:
np.median(b)

18.5

In [8]:
# cumsum 
np.cumsum(a)

array([ 11,  33,  66, 110])

In [9]:
a

array([[11, 22],
       [33, 44]])

In [10]:
11 + 22 + 33 + 44

110

In [11]:
a.sum()

110

In [12]:
# corrcoef
np.corrcoef(a)

array([[1., 1.],
       [1., 1.]])

In [13]:
# std 
np.std(b)

10.88577052853862

In [14]:
# max , min 
np.max(a)

44

In [15]:
a.max(axis=1)

array([22, 44])

In [16]:
b.min(axis=0)

array([12, 24])

In [17]:
b[0]

array([12, 24])

### copy and sorting arrays

In [18]:
d = c.copy()
d

array([[23, 46],
       [46, 83]])

In [19]:
d[0][1] = 50
d

array([[23, 50],
       [46, 83]])

In [20]:
c

array([[23, 46],
       [46, 83]])

In [21]:
# view 
f = d.view()
f

array([[23, 50],
       [46, 83]])

In [22]:
d

array([[23, 50],
       [46, 83]])

In [23]:
f[0][0]= 100
f

array([[100,  50],
       [ 46,  83]])

In [24]:
d

array([[100,  50],
       [ 46,  83]])

In [25]:
d.sort()

In [26]:
d

array([[ 50, 100],
       [ 46,  83]])

In [27]:
c.sort(axis=0)

In [28]:
c

array([[23, 46],
       [46, 83]])

In [29]:
np.sort(d, axis=0)

array([[ 46,  83],
       [ 50, 100]])

## Array Manipulations

In [57]:
# transpose
np.transpose(a)

array([[11, 33],
       [22, 44]])

In [31]:
a

array([[11, 22],
       [33, 44]])

In [32]:
a.T

array([[11, 33],
       [22, 44]])

In [33]:
# reshape(-neg) --  flatten the array
c.reshape(-1)

array([23, 46, 46, 83])

In [59]:
# flatten 
c.flatten()

array([23, 46, 46, 83])

In [35]:
# ravel
c.ravel()

array([23, 46, 46, 83])

In [36]:
# nditer
for i in c:
    print(i)

[23 46]
[46 83]


In [37]:
for element in np.nditer(c):
    print(element)

23
46
46
83


In [62]:
# append
arr = np.append(arr=arr,values=[12,13,14])
arr

array([22,  7,  6,  2,  3,  4, 12, 13, 14])

In [63]:
arr

array([22,  7,  6,  2,  3,  4, 12, 13, 14])

In [40]:
np.append(arr=c, values=np.array([[12,13]]), axis= 0)

array([[23, 46],
       [46, 83],
       [12, 13]])

In [64]:
#insert
np.insert(c, 1, 5, axis= 1)

array([[23,  5, 46],
       [46,  5, 83]])

In [42]:
# delete
np.delete(c,0)

array([46, 46, 83])

In [43]:
# concatenation

np.concatenate((a,b),axis=0)

array([[11, 22],
       [33, 44],
       [12, 24],
       [13, 39]])

In [44]:
np.concatenate((a,b),axis=1)

array([[11, 22, 12, 24],
       [33, 44, 13, 39]])

In [45]:
# hstack
np.hstack((a,b))

array([[11, 22, 12, 24],
       [33, 44, 13, 39]])

In [46]:
# vstack
np.vstack((a,b))

array([[11, 22],
       [33, 44],
       [12, 24],
       [13, 39]])

In [65]:
X = np.arange(16).reshape(4,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
np.split(X,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [49]:
# hsplit
np.hsplit(X,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [50]:
# vsplit
np.vsplit(X,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [51]:
# array_split
np.array_split(c,5)

[array([[23, 46]]),
 array([[46, 83]]),
 array([], shape=(0, 2), dtype=int64),
 array([], shape=(0, 2), dtype=int64),
 array([], shape=(0, 2), dtype=int64)]

In [52]:
# info
np.iinfo(int)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [53]:
# finfo
np.finfo(float)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [73]:
# resize
np.resize(a = [[1,2], [3,4]], new_shape=(8,5))

array([[1, 2, 3, 4, 1],
       [2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3],
       [4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1],
       [2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3],
       [4, 1, 2, 3, 4]])