# Phase-3(Array manipulation,I/o with numpy array)

In [1]:
import numpy as np

In [2]:
a=np.array([[11,22],[33,44]])
a

array([[11, 22],
       [33, 44]])

In [3]:
#transpose of array is similar as matrix transpose
np.transpose(a)

array([[11, 33],
       [22, 44]])

In [4]:
a.T#it also gives transpose matrix

array([[11, 33],
       [22, 44]])

In [5]:
c=np.array([[23,46],[46,83]])

In [6]:
c

array([[23, 46],
       [46, 83]])

In [8]:
#flatten() method simpli converted to 1-D array
c.flatten()

array([23, 46, 46, 83])

In [9]:
#ravel(),reshape(-1) methodes are also convert array to 1-D array
c.ravel()

array([23, 46, 46, 83])

In [10]:
c.reshape(-1)

array([23, 46, 46, 83])

In [11]:
#nditer
for i in c:
    print(i)

[23 46]
[46 83]


In [12]:
#for printing the element of the array
for element in np.nditer(c):
    print(element)

23
46
46
83


In [13]:
#append() used to concadinate purpose
np.append(arr=np.array([22,7,6]),values=[2,3,4])


array([22,  7,  6,  2,  3,  4])

In [14]:
#but for specific row or column appending
c

array([[23, 46],
       [46, 83]])

In [15]:
np.append(arr=c,values=np.array([[12,13]]),axis=0)#add row wise

array([[23, 46],
       [46, 83],
       [12, 13]])

In [17]:
np.append(arr=c,values=np.array([[50],[100]]),axis=1)

array([[ 23,  46,  50],
       [ 46,  83, 100]])

In [18]:
#insert() method
c

array([[23, 46],
       [46, 83]])

In [19]:
np.insert(c,1,5,axis=0)#here 1 after 'c' gives the index numkber of row

array([[23, 46],
       [ 5,  5],
       [46, 83]])

In [20]:
np.insert(c,1,10,axis=1)

array([[23, 10, 46],
       [46, 10, 83]])

In [21]:
#delete()
c

array([[23, 46],
       [46, 83]])

In [22]:
np.delete(c,0)

array([46, 46, 83])

In [23]:
#concatenation
a=np.array([[11,22],[33,44]])
a

array([[11, 22],
       [33, 44]])

In [24]:
b=np.array([[12,24],[13,39]])
b

array([[12, 24],
       [13, 39]])

In [26]:
np.concatenate((a,b))

array([[11, 22],
       [33, 44],
       [12, 24],
       [13, 39]])

In [27]:
np.concatenate((a,b),axis=0)# col wise

array([[11, 22],
       [33, 44],
       [12, 24],
       [13, 39]])

In [28]:
np.concatenate((a,b),axis=1)#row wise

array([[11, 22, 12, 24],
       [33, 44, 13, 39]])

In [29]:
#hstack() method also concatenate arrays in horizontally
np.hstack((a,b))

array([[11, 22, 12, 24],
       [33, 44, 13, 39]])

In [30]:
np.vstack((a,b))#concatenate vertically

array([[11, 22],
       [33, 44],
       [12, 24],
       [13, 39]])

In [31]:
#split( metod)#create equally divided array
x=np.arange(16)

In [32]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
x=np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
np.split(x,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [35]:
#hsplit() metod split the array horizontally
np.hsplit(x,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [36]:
np.vsplit(x,2)#split vertically

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [37]:
#array_split()
c

array([[23, 46],
       [46, 83]])

In [38]:
np.array_split(c,5)

[array([[23, 46]]),
 array([[46, 83]]),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32)]

In [39]:
#resize() metode
np.resize(a=[32],new_shape=(2,5))#2 row and 5 col.

array([[32, 32, 32, 32, 32],
       [32, 32, 32, 32, 32]])

In [40]:
np.resize(a=[1,2,3,4,5],new_shape=(5,4))

array([[1, 2, 3, 4],
       [5, 1, 2, 3],
       [4, 5, 1, 2],
       [3, 4, 5, 1],
       [2, 3, 4, 5]])