In [1]:
import numpy as nu
nu.__version__

'1.21.4'

# numpy

In [2]:
dir(nu)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


# dimension of the array

In [5]:
arr=nu.array([1,2,3]) #1-D array
arr

array([1, 2, 3])

calculating dimension of the array using #ndmin and #ndim

In [6]:
arr.ndim

1

In [7]:
arr=nu.array([[0,0,0]])
arr

array([[0, 0, 0]])

In [8]:
arr.ndim

2

In [10]:
arr_2d=nu.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr_2d.ndim

2

In [12]:
arr_3d=nu.array([[[1,2],[3,4],[5,6]]])
arr_3d

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [13]:
arr_3d.ndim

3

you can have a zero dimension array.

In [14]:
nu.array(50)


array(50)

In [15]:
nu.array(50).ndim

0

# Inspection of Array

In [16]:
arr

array([[0, 0, 0]])

In [17]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr_3d

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [19]:
len(arr)# gives the length of the array

1

In [20]:
len(arr_2d)

2

In [21]:
len(arr_3d)

1

In [22]:
arr_2d.shape

(2, 3)

In [26]:
arr.size #gives the number of element in a array

3

In [24]:
arr_2d.size

6

In [25]:
arr_3d.size

6

In [27]:
arr_3d.shape

(1, 3, 2)

In [28]:
arr_2d.dtype

dtype('int32')

In [29]:
arr_3d.dtype

dtype('int32')

In [30]:
arr_2d.dtype.name

'int32'

# change the element type of array

In [31]:
nu.array([True,False]).astype('int')

array([1, 0])

In [33]:
nu.array([3.12,1.2]).astype('int')#float to int

array([3, 1])

In [34]:
nu.array([2,3,4],ndmin=5)

array([[[[[2, 3, 4]]]]])

# Array Mathematices

In [35]:
a=nu.array([1,2,3])
b=nu.array([4,5,6])

In [36]:
nu.add(a,b)

array([5, 7, 9])

In [37]:
a+b

array([5, 7, 9])

In [38]:
a-b

array([-3, -3, -3])

In [41]:
a*b

array([ 4, 10, 18])

In [42]:
a/b

array([0.25, 0.4 , 0.5 ])

In [43]:
a**b

array([  1,  32, 729], dtype=int32)

In [44]:
a%b

array([1, 2, 3], dtype=int32)

In [45]:
b%a

array([0, 1, 0], dtype=int32)

In [46]:
nu.multiply(a,b)

array([ 4, 10, 18])

In [47]:
nu.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [55]:
import numpy as nu

In [56]:
nu.__version__

'1.21.4'

In [57]:
a=nu.array([1,2,3])
b=nu.array([4,5,6])

In [58]:
nu.exp(b)

array([ 54.59815003, 148.4131591 , 403.42879349])

In [59]:
nu.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [60]:
nu.sin(b)

array([-0.7568025 , -0.95892427, -0.2794155 ])

In [61]:
nu.dot(a,b)

32

In [62]:
nu.sin(nu.tan(b))

array([ 0.91593089,  0.23665573, -0.28691626])