# Initial placeholders

In [1]:
import numpy as nu

In [3]:
arr=nu.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr.shape

(2, 3)

In [5]:
arr.size

6

In [6]:
arr.dtype

dtype('int32')

In [7]:
len(arr)

2

# ##methodes used 
 1.zeros()

In [10]:
nu.zeros(4)#gives a array containing the zero value only and gives float value

array([0., 0., 0., 0.])

In [11]:
nu.zeros(4).astype('int')

array([0, 0, 0, 0])

In [13]:
nu.zeros([3,4])#gives array of 3 row and 4 col

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
nu.zeros([3,4]).astype('int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
nu.zeros([2,3,4])#gives a 2-d array of 3 row and 4 col

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

2.ones()

In [16]:
nu.ones(3)

array([1., 1., 1.])

In [17]:
nu.ones(3).astype('int')

array([1, 1, 1])

In [18]:
nu.ones([3,4]).astype('int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
nu.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

3.identity matrix

In [20]:
nu.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
nu.eye(3).astype('int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [23]:
nu.eye(N=2,M=4)#N-no. of row or no. ones contain and M-no.col

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [25]:
nu.eye(N=2,M=4).astype('int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0]])

In [28]:
nu.eye(N=2,M=4,k=1)#HERE k-IS THE INDEXPOINT OF STARTING THE ONE VALUE

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [29]:
nu.eye(N=2,M=4,k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
nu.eye(N=2,M=4,k=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

4.arange()

In [32]:
nu.arange(5,11)#here it mention start and end point respectivly

array([ 5,  6,  7,  8,  9, 10])

In [34]:
nu.arange(5,11,1)#1- is the interval

array([ 5,  6,  7,  8,  9, 10])

In [35]:
nu.arange(20,40,5)

array([20, 25, 30, 35])

5.linspace()

In [36]:
nu.linspace(start=5,stop=6)#gives 50 value of eqal difference

array([5.        , 5.02040816, 5.04081633, 5.06122449, 5.08163265,
       5.10204082, 5.12244898, 5.14285714, 5.16326531, 5.18367347,
       5.20408163, 5.2244898 , 5.24489796, 5.26530612, 5.28571429,
       5.30612245, 5.32653061, 5.34693878, 5.36734694, 5.3877551 ,
       5.40816327, 5.42857143, 5.44897959, 5.46938776, 5.48979592,
       5.51020408, 5.53061224, 5.55102041, 5.57142857, 5.59183673,
       5.6122449 , 5.63265306, 5.65306122, 5.67346939, 5.69387755,
       5.71428571, 5.73469388, 5.75510204, 5.7755102 , 5.79591837,
       5.81632653, 5.83673469, 5.85714286, 5.87755102, 5.89795918,
       5.91836735, 5.93877551, 5.95918367, 5.97959184, 6.        ])

In [37]:
nu.linspace(10,100,num=10)#num is the numbers of number we want bet. 10 and 100

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [38]:
nu.linspace(10,100,num=10,retstep=True)#retstep give the eqaly diff. value of the array

(array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]), 10.0)

In [39]:
nu.linspace(10,100,num=10,endpoint=False,retstep=True)#it gives 10 number bet. 10 and 100 difference of 9

(array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.]), 9.0)

6.full()

In [41]:
nu.full(shape=2,fill_value=5)

array([5, 5])

In [43]:
nu.full(shape=[2,2],fill_value=7)

array([[7, 7],
       [7, 7]])

7.empty()

In [44]:
nu.empty(2)

array([1.20481864e-311, 0.00000000e+000])

In [45]:
nu.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

8.random()

In [46]:
nu.random.randint(2,3)#it gives a integer value between 2 and 3

2

In [48]:
nu.random.randn()#it gives any standard value

1.1781952343817073

In [49]:
nu.random.random()#gives random value between 0 and 1

0.661087104846507

# Aggrement function

In [50]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

1.sum

In [51]:
arr.sum(axis=0)#give sum colum,n wise

array([5, 7, 9])

In [52]:
arr.sum(axis=1)#gives sum row wise

array([ 6, 15])

In [53]:
arr.sum(axis=1)[0]#sum of row-1

6

In [54]:
arr.sum(axis=1)[1]

15

In [55]:
arr.sum(axis=0)[0]

5

In [56]:
arr.sum(axis=0)[1]

7

2.mean

In [57]:
arr.mean()

3.5

In [58]:
arr.mean(axis=0)

array([2.5, 3.5, 4.5])

In [59]:
arr.mean(axis=1)

array([2., 5.])

3.mode()

In [60]:
from scipy import stats
stats.mode(arr)

ModeResult(mode=array([[1, 2, 3]]), count=array([[1, 1, 1]]))

4.median

In [62]:
nu.median(arr)

3.5

# min max

In [63]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
arr.max()

6

In [66]:
arr.max(axis=0)

array([4, 5, 6])

In [67]:
arr.max(axis=1)

array([3, 6])

In [68]:
arr.min()

1

In [69]:
arr.min(axis=0)

array([1, 2, 3])

# cumulative sum(cumsum)

In [70]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr.cumsum()#1,1+2,3+3....

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

standard deviation(std())

In [73]:
arr.std()

1.707825127659933

# comparision

In [74]:
arr1=nu.array([[2,3,-90],[-40,5,-45]])
arr1

array([[  2,   3, -90],
       [-40,   5, -45]])

In [75]:
arr>arr1#element wise coparision

array([[False, False,  True],
       [ True, False,  True]])

In [76]:
arr<3

array([[ True,  True, False],
       [False, False, False]])

In [77]:
nu.array_equal(arr,arr1)#array wise comparision

False

# sorting of array 

In [78]:
#column wise sorting i.e. small value element at 1st pos.
arr1.sort(axis=0)

In [79]:
arr1

array([[-40,   3, -90],
       [  2,   5, -45]])

In [82]:
#row wise
arr1.sort(axis=1)

In [83]:
arr1

array([[-90, -40,   3],
       [-45,   2,   5]])

In [85]:
#whole array is aort
arr.sort()
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
arr1.sort()
arr1

array([[-90, -40,   3],
       [-45,   2,   5]])

# copy()

In [87]:
arc=arr.copy()

In [88]:
arc

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
arc[0]=5

In [90]:
arc

array([[5, 5, 5],
       [4, 5, 6]])

In [93]:
arc[0][2]=95

In [94]:
arc

array([[ 5,  5, 95],
       [ 4,  5,  6]])

In [95]:
arr#here no main array element should not change

array([[1, 2, 3],
       [4, 5, 6]])

# view()

In [96]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
arv=arr.view()

In [98]:
arv

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
arv[0][2]=95

In [100]:
arv

array([[ 1,  2, 95],
       [ 4,  5,  6]])

In [101]:
arr#but here original array element changed as arv element changed

array([[ 1,  2, 95],
       [ 4,  5,  6]])